# If you come from bash you might have to change your $PATH.
# export PATH=$HOME/bin:/usr/local/bin:$PATH

# Path to your oh-my-zsh installation.
  export ZSH="/home/david/.oh-my-zsh"

# Set name of the theme to load --- if set to "random", it will
# load a random theme each time oh-my-zsh is loaded, in which case,
# to know which specific one was loaded, run: echo $RANDOM_THEME
# See https://github.com/robbyrussell/oh-my-zsh/wiki/Themes
# ZSH_THEME="avit"

# Set list of themes to pick from when loading at random
# Setting this variable when ZSH_THEME=random will cause zsh to load
# a theme from this variable instead of looking in ~/.oh-my-zsh/themes/
# If set to an empty array, this variable will have no effect.
# ZSH_THEME_RANDOM_CANDIDATES=("af-magic")

# Uncomment the following line to use case-sensitive completion.
# CASE_SENSITIVE="true"

# Uncomment the following line to use hyphen-insensitive completion.
# Case-sensitive completion must be off. _ and - will be interchangeable.
# HYPHEN_INSENSITIVE="true"

# Uncomment the following line to disable bi-weekly auto-update checks.
# DISABLE_AUTO_UPDATE="true"

# Uncomment the following line to automatically update without prompting.
# DISABLE_UPDATE_PROMPT="true"

# Uncomment the following line to change how often to auto-update (in days).
# export UPDATE_ZSH_DAYS=13

# Uncomment the following line to disable colors in ls.
# DISABLE_LS_COLORS="true"

# Uncomment the following line to disable auto-setting terminal title.
# DISABLE_AUTO_TITLE="true"

# Uncomment the following line to enable command auto-correction.
# ENABLE_CORRECTION="true"

# Uncomment the following line to display red dots whilst waiting for completion.
# COMPLETION_WAITING_DOTS="true"

# Uncomment the following line if you want to disable marking untracked files
# under VCS as dirty. This makes repository status check for large repositories
# much, much faster.
# DISABLE_UNTRACKED_FILES_DIRTY="true"

# Uncomment the following line if you want to change the command execution time
# stamp shown in the history command output.
# You can set one of the optional three formats:
# "mm/dd/yyyy"|"dd.mm.yyyy"|"yyyy-mm-dd"
# or set a custom format using the strftime function format specifications,
# see 'man strftime' for details.
# HIST_STAMPS="mm/dd/yyyy"

# Would you like to use another custom folder than $ZSH/custom?
# ZSH_CUSTOM=/path/to/new-custom-folder

# Which plugins would you like to load?
# Standard plugins can be found in ~/.oh-my-zsh/plugins/*
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
# Add wisely, as too many plugins slow down shell startup.
plugins=(git vi-mode zsh-syntax-highlighting docker)

source $ZSH/oh-my-zsh.sh

# User configuration

# export MANPATH="/usr/local/man:$MANPATH"

# You may need to manually set your language environment
# export LANG=en_US.UTF-8

 #Preferred editor for local and remote sessions
 if [[ -n $SSH_CONNECTION ]]; then
   export EDITOR='vim'
 else
   export EDITOR='nvim'
 fi

# Compilation flags
# export ARCHFLAGS="-arch x86_64"

# Set personal aliases, overriding those provided by oh-my-zsh libs,
# plugins, and themes. Aliases can be placed here, though oh-my-zsh
# users are encouraged to define aliases within the ZSH_CUSTOM folder.
# For a full list of active aliases, run `alias`.
#
# Example aliases
# alias zshconfig="mate ~/.zshrc"
# alias ohmyzsh="mate ~/.oh-my-zsh"

alias vim="nvim.appimage"
alias gvim="nvim-gtk"
alias yarn="yarnpkg"
# Put on /home/david/local/bin david specific binaries like nvim
export PATH=/home/david/.usr/local/bin:/usr/local/bin:$HOME/.yarn/bin:$HOME/.config/yarn/global/node_modules/.bin/:$PATH
export PATH=$PATH:/home/david/.local/bin
export PATH=$PATH:/usr/local/go/bin
export PATH=$PATH:/home/david/.local/go/bin/:/home/david/projects/Go/bin
export PATH=$PATH:/home/david/.local/go/bin/:/home/david/projects/Go/src/core/bin
export PATH=$PATH:/home/david/projects/learning/datascience/anaconda3/bin
export PATH=/home/david/.java/jdk1.8.0_231/bin:/home/david/.gradle/gradle-5.6.3/bin:$PATH
export PATH=/home/david/projects/pencillabs/ej/ej-components/conversations/node_modules/@stencil/core/bin:$PATH

#pyenv configuration
export PATH=/home/david/.pyenv/bin:$PATH
eval "$(pyenv init -)"

export JAVA_HOME=~/.java/jdk1.8.0_231/
export ANDROID_HOME=/home/david/Android/Sdk/
export ANDROID_SDK_ROOT=/home/david/Android/Sdk/
export GOPATH=/home/david/projects/Go/
export WORKON_HOME=$HOME/projects/.virtualenvs
export AIRFLOW_HOME=~/projects/pencillabs/ej/ds-stack/
source /home/david/.local/bin/virtualenvwrapper.sh

function dcexec() {
	container_to_exec=$(docker container ls | fzf | awk '{print $1}')
	if [ ! -z "$container_to_exec" ]; then
		docker exec -it $container_to_exec bash
	fi
}
function dirm() {
	image_to_remove=$(docker image ls --format "table {{.Repository}}\t{{ .ID }}" | fzf | sed 's#.*\s##')
	if [ ! -z "$image_to_remove" ]; then
		docker image rm $image_to_remove --force
	fi
}

function dvrm() {
	volume_to_remove=$(docker volume ls | fzf | sed 's#.*\s##')
	if [ ! -z "$volume_to_remove" ]; then
		docker volume rm $volume_to_remove --force
	fi
}
function dils() {
	docker image ls | fzf
}

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

# zsh theme: https://github.com/sindresorhus/pure
fpath+=$HOME/.zsh/pure
autoload -U promptinit; promptinit
prompt pure
