# ~/.tmuxinator/bp.yml

name: bp
root: ~/Projetos/pencillabs/brparticipativo

windows:
  - vim:
      root: ~/Projetos/pencillabs/brparticipativo/
      layout: ad2e,213x50,0,0{160x50,0,0,1,52x50,161,0,13}
      panes:
        - 
        -
  - ej:
      layout: 2482,213x50,0,0{144x50,0,0,21,68x50,145,0[68x25,145,0,78,68x24,145,26,79]}
      root: ~/Projetos/pencillabs/brparticipativo/ej/ej-application
      panes:
        -
        -
        -
  - media-api:
      layout: 2482,213x50,0,0{144x50,0,0,21,68x50,145,0[68x25,145,0,78,68x24,145,26,79]}
      root: ~/Projetos/pencillabs/brparticipativo/multi-channel-participation
      panes:
        -
        -
        -
