# ~/.tmuxinator/conecta.yml

name: conecta
root: ~/Projetos/pencillabs/fundacaolemann/ambientevirtual/

windows:
  - vim:
      root: ~/Projetos/pencillabs/fundacaolemann/ambientevirtual/plataforma-rede-de-lideres/
      layout: 7331,213x50,0,0{151x50,0,0,16,61x50,152,0,19}
      panes:
        - source ~/Projetos/virtualenvs/conecta/bin/activate && vim
        - opencode --port 
  - server:
      root: ~/Projetos/pencillabs/fundacaolemann/ambientevirtual/plataforma-rede-de-lideres/
      layout: 2482,213x50,0,0{144x50,0,0,21,68x50,145,0[68x25,145,0,78,68x24,145,26,79]}
      panes:
        - source ~/Projetos/virtualenvs/conecta/bin/activate
        - source ~/Projetos/virtualenvs/conecta/bin/activate
        -
  - ssh:
      panes:
        - ssh ambientevirtual-vpn
