# /home/davidcarlos/.tmuxinator/pencil-site.yml

name: pencil-site
root: ~/Projetos/pencillabs/pencillabs/

windows:
  - vim:
      layout: a425,213x50,0,0[213x35,0,0,20,213x14,0,36{106x14,0,36,26,106x14,107,36,29}]
      panes:
        - source ~/Projetos/virtualenvs/pencil-site/bin/activate && vim
        - 
        -
  - server:
      layout: a425,213x50,0,0[213x35,0,0,20,213x14,0,36{106x14,0,36,26,106x14,107,36,29}]
      panes:
        - make up
        -
        -
