# /home/davidcarlos/.tmuxinator/pencil-site.yml

name: pencil-site
root: ~/Projetos/pencillabs/sites/pencillabs

windows:
  - vim:
      panes:
        - vim
  - server:
      layout: 13cd,192x46,0,0[192x23,0,0,14,192x22,0,24{96x22,0,24,15,95x22,97,24,16}]
      panes:
        - make up
        -
        -
