# /home/davidcarlos/.tmuxinator/pencil-site.yml

name: pencil-site
root: ~/Projetos/pencillabs/sites/pencillabs/

windows:
  - vim:
      layout: 445e,213x50,0,0{155x50,0,0,63,57x50,156,0,69}
      panes:
        - source ~/Projetos/virtualenvs/pencillabs-site/bin/activate && vim
        - 
  - server:
      layout: 7d6a,213x50,0,0{139x50,0,0,64,73x50,140,0[73x25,140,0,70,73x24,140,26,71]}
      panes:
        - make up
        -
        -
