# /home/davidcarlos/.tmuxinator/sdcl.yml

name: sdcl
root: ~/Projetos/pencillabs/SEDUC/


windows:
  - vim:
      layout: dfd1,213x55,0,0[213x41,0,0,3,213x13,0,42,7]
      panes:
        - vim
        - cd sdcl
  - server: 
      layout: bcc2,213x55,0,0[213x38,0,0,4,213x16,0,39{106x16,0,39,5,106x16,107,39,6}]
      panes:
        -
        -
        -
