
[env]
term = "alacritty"


[window]
decorations = "None"
opacity = 0.9

[font]
size = 12
normal = {family = "JetBrainsMono Nerd Font"}
bold = {family = "JetBrainsMono Nerd Font"}
italic = {family = "JetBrainsMono Nerd Font"}

[[keyboard.bindings]]
action = "ToggleFullscreen"
key = "F11"

[general]
import = ["~/.config/alacritty/alacritty-nord.toml"]
