
[env]
term = "alacritty"


[window]
decorations = "None"

[font]
size = 11.5
normal = {family = "JetBrainsMono Nerd Font"}
bold = {family = "JetBrainsMono Nerd Font"}
italic = {family = "JetBrainsMono Nerd Font"}

[[keyboard.bindings]]
action = "ToggleFullscreen"
key = "F11"

[general]
import = ["~/.config/alacritty/alacritty-solarized.toml"]
