export ZSH="/home/davidcarlos/.oh-my-zsh"

plugins=(git vi-mode docker fzf)

source $ZSH/oh-my-zsh.sh

 if [[ -n $SSH_CONNECTION ]]; then
   export EDITOR='vim'
 else
   export EDITOR='nvim'
 fi


alias k="kubectl"
alias vim="nvim.appimage"
alias k="kubectl"
alias gvim="nvim-gtk"
alias keepass="~/.local/bin/KeePassXC-2.6.4-x86_64.AppImage"
# https://github.com/sharkdp/bat
alias cat="bat"
export BAT_THEME=gruvbox-dark

# Put on /home/davidcarlos/local/bin davidcarlos specific binaries like nvim
export PATH=/home/davidcarlos/.local/bin:/usr/local/bin:$HOME/.yarn/bin:$HOME/.config/yarn/global/node_modules/.bin/:$PATH
export PATH=$PATH:/home/davidcarlos/.local/bin
export PATH=$PATH:/usr/local/go/bin
export PATH=$PATH:/home/davidcarlos/.local/go/bin/:/home/davidcarlos/projects/Go/bin
export PATH=$PATH:/home/davidcarlos/.local/go/bin/:/home/davidcarlos/projects/Go/src/core/bin
export PATH=$PATH:/home/davidcarlos/projects/learning/datascience/anaconda3/bin
export PATH=/home/davidcarlos/.java/jdk1.8.0_231/bin:/home/davidcarlos/.gradle/gradle-5.6.3/bin:$PATH
export PATH=/home/davidcarlos/projects/pencillabs/ej/ej-components/conversations/node_modules/@stencil/core/bin:$PATH
export PATH=/home/davidcarlos/Ferramentas/diff-so-fancy/:$PATH
export PATH=/home/davidcarlos/.cargo/bin:$PATH
export PATH=/home/davidcarlos/bin:$PATH
export JAVA_HOME=~/.jdks/corretto-16.0.2/
export ANDROID_HOME=/home/davidcarlos/Android/Sdk/
export ANDROID_SDK_ROOT=/home/davidcarlos/Android/Sdk/
export GOPATH=/home/davidcarlos/Projetos/pencillabs/infra
export WORKON_HOME=$HOME/projects/.virtualenvs
export AIRFLOW_HOME=~/projects/pencillabs/ej/ds-stack/
export GO111MODULE=auto

# ALT-c: find directories and hit <enter> to cd directory
# Ctrl-r: run fzf on shell history
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh &&

# zsh prompt: https://github.com/sindresorhus/pure
fpath+=($HOME/.zsh/pure)
autoload -U promptinit; promptinit
prompt pure

# Remaps Altgr + R to print |.
# Logitech k380 does not have a pipe key if you use an abnt2 layout
# more infos: https://dev.to/nfo94/como-remapear-teclas-no-linux-46p8
# xmodmap does not works on Wayland.
xmodmap -e "keycode 27 = r R r R bar"

# Better replacement for ls -> https://github.com/ogham/exa
if [ "$(exa --help)" ]; then
	alias ls="exa --long --icons --git --sort=modified"
fi

export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion

[[ $commands[kubectl] ]] && source <(kubectl completion zsh)

# Add RVM to PATH for scripting. Make sure this is the last PATH variable change.
export PATH="$PATH:$HOME/.rvm/bin"
source ~/.rvm/scripts/rvm
