---
- name: Install packages
  hosts: localhost

  tasks:
    - name: Install gcc package
      become: true
      ansible.builtin.dnf:
        name: gcc

    - name: Install fuse-libs package
      become: true
      ansible.builtin.dnf:
        name: fuse-libs

    - name: Install python3-libdnf5 package
      become: true
      ansible.builtin.dnf:
        name: python3-libdnf5

    - name: Install git package
      become: true
      ansible.builtin.dnf:
        name: git

    - name: Install curl package
      become: true
      ansible.builtin.dnf:
        name: curl

    # Required by the AppImageLauncher binary
    - name: Install libgpg-error.so.0
      become: true
      ansible.builtin.dnf:
        name: libgpg-error.so.0

    # a better htop version
    - name: Install btop package
      become: true
      ansible.builtin.dnf:
        name: btop

    - name: Install keepassxc package
      become: true
      ansible.builtin.dnf:
        name: keepassxc

    - name: Install flameshot package
      become: true
      ansible.builtin.dnf:
        name: flameshot

    - name: Install Simple Screen Recorder package
      become: true
      ansible.builtin.dnf:
        name: simplescreenrecorder

    - name: Install flatpak package
      become: true
      ansible.builtin.dnf:
        name: flatpak

    - name: Install apostrophe package
      ansible.builtin.shell: |
        flatpak install flathub org.gnome.gitlab.somas.Apostrophe

    - name: Install Roboto font
      become: true
      ansible.builtin.dnf:
        name: google-roboto-fonts

    - name: Install Fira Sans font
      become: true
      ansible.builtin.dnf:
        name: mozilla-fira-sans-fonts

    - name: Creates custom fonts directory
      ansible.builtin.file:
        path: ~/.fonts
        state: directory
        mode: "0755"

    - name: Download JetBrainsMono font
      ansible.builtin.unarchive:
        src: https://github.com/ryanoasis/nerd-fonts/releases/download/v3.3.0/JetBrainsMono.zip
        dest: ~/.fonts/
        remote_src: yes

    - name: Rebuild fonts cache
      ansible.builtin.shell:
        cmd: fc-cache -f -v

    # Improves the Appimage integration with XFCE4
    - name: Download AppImageLauncher
      ansible.builtin.uri:
        url: https://github.com/TheAssassin/AppImageLauncher/releases/download/v3.0.0-alpha-4/appimagelauncher_3.0.0-alpha-4-gha253.36951ec_x86_64.rpm
        dest: ~/.local/bin
        mode: "755"
    - name: Install AppImageLauncher
      community.general.apt_rpm:
        pkg:
          - ~/.local/bin/appimagelauncher_3.0.0-alpha-4-gha253.36951ec_x86_64.rpm
        state: present

    - name: Run appimaged daemon
      ansible.builtin.shell:
        cmd: ~/.local/bin/appimaged-866-x86_64.AppImage

    - name: Creates pencillabs projects directory
      ansible.builtin.file:
        path: ~/Projetos/pencillabs/
        state: directory
        mode: "0755"

    # Fedora only
    - name: Set timezone
      become: true
      ansible.builtin.shell:
        cmd: timedatectl set-timezone America/Sao_Paulo

    # Fedora only
    - name: Set locale
      become: true
      ansible.builtin.shell:
        cmd: localectl set-locale LANG=pt_BR.UTF-8
