---
- name: Install packages
  hosts: localhost

  tasks:
    - name: Install gcc package
      become: true
      ansible.builtin.dnf:
        name: gcc

    - name: Install fuse-libs package
      become: true
      ansible.builtin.dnf:
        name: fuse-libs

    - name: Install python3-libdnf5 package
      become: true
      ansible.builtin.dnf:
        name: python3-libdnf5

    - name: Install git package
      become: true
      ansible.builtin.dnf:
        name: git

    - name: Install curl package
      become: true
      ansible.builtin.dnf:
        name: curl

    - name: Install htop package
      become: true
      ansible.builtin.dnf:
        name: htop

    - name: Install keepassxc package
      become: true
      ansible.builtin.dnf:
        name: keepassxc

    - name: Install flameshot package
      become: true
      ansible.builtin.dnf:
        name: flameshot

    - name: Install flatpak package
      become: true
      ansible.builtin.dnf:
        name: flatpak

    - name: Install Roboto font
      become: true
      ansible.builtin.dnf:
        name: google-roboto-fonts

    - name: Install Fira Sans font
      become: true
      ansible.builtin.dnf:
        name: mozilla-fira-sans-fonts

    - name: Creates custom fonts directory
      ansible.builtin.file:
        path: ~/.fonts
        state: directory
        mode: "0755"

    - name: Download JetBrainsMono font
      ansible.builtin.unarchive:
        src: https://github.com/ryanoasis/nerd-fonts/releases/download/v3.3.0/JetBrainsMono.zip
        dest: ~/.fonts/
        remote_src: yes

    - name: Rebuild fonts cache
      ansible.builtin.shell:
        cmd: fc-cache -f -v

    - name: Download appimaged daemon
      ansible.builtin.uri:
        url: https://github.com/probonopd/go-appimage/releases/download/continuous/appimaged-866-x86_64.AppImage
        dest: ~/.local/bin
        mode: "755"

    - name: Run appimaged daemon
      ansible.builtin.shell:
        cmd: ~/.local/bin/appimaged-866-x86_64.AppImage

    - name: Creates pencillabs projects directory
      ansible.builtin.file:
        path: ~/Projetos/pencillabs/
        state: directory
        mode: "0755"
