---
- name: Install packages
  hosts: localhost

  tasks:
    - name: Install gcc package
      become: true
      ansible.builtin.dnf:
        name: gcc

    - name: Install fuse-libs package
      become: true
      ansible.builtin.dnf:
        name: fuse-libs

    - name: Install python3-libdnf5 package
      become: true
      ansible.builtin.dnf:
        name: python3-libdnf5

    - name: Install git package
      become: true
      ansible.builtin.dnf:
        name: git

    - name: Install curl package
      become: true
      ansible.builtin.dnf:
        name: curl


    - name: Install htop package
      become: true
      ansible.builtin.dnf:
        name: htop

    - name: Install keepassxc package
      become: true
      ansible.builtin.dnf:
        name: keepassxc

    - name: Install rofi package
      become: true
      ansible.builtin.dnf:
        name: rofi

    - name: Install flatpak package
      become: true
      ansible.builtin.dnf:
        name: flatpak
