---
- name: Install packages
  hosts: localhost

  tasks:
    - name: Install git
      become: true
      ansible.builtin.dnf:
        name: git

    - name: Install curl
      become: true
      ansible.builtin.dnf:
        name: curl

    - name: Install tmux
      become: true
      ansible.builtin.dnf:
        name: tmux

    - name: Install htop
      become: true
      ansible.builtin.dnf:
        name: htop

    - name: Install alacrity
      become: true
      ansible.builtin.dnf:
        name: alacrity

    - name: Install keepassxc
      become: true
      ansible.builtin.dnf:
        name: keepassxc
