---
- name: Install Python packages
  hosts: localhost

  tasks:
    # pyenv dependency
    - name: Install zlib-devel package
      become: true
      ansible.builtin.dnf:
        name: zlib-devel

    # pyenv dependency (lzma)
    - name: Install lzma package
      become: true
      ansible.builtin.dnf:
        name: xz-devel

    # pyenv dependency
    - name: Install lzma package
      become: true
      ansible.builtin.dnf:
        name: libffi-devel

    # pyenv dependency
    - name: Install bzip2-devel package
      become: true
      ansible.builtin.dnf:
        name: bzip2-devel
        #
    # pyenv dependency
    - name: Install openssl-devel package
      become: true
      ansible.builtin.dnf:
        name: openssl-devel

    # pyenv dependency
    - name: Install sqlite-devel package
      become: true
      ansible.builtin.dnf:
        name: sqlite-devel

    # pyenv dependency
    - name: Install ncurses-devel package
      become: true
      ansible.builtin.dnf:
        name: ncurses-devel

    # pyenv dependency
    - name: Install readline-devel package
      become: true
      ansible.builtin.dnf:
        name: readline-devel

    # pyenv dependency
    - name: Install tk-devel package
      become: true
      ansible.builtin.dnf:
        name: tk-devel

    - name: Install pipx package
      become: true
      ansible.builtin.dnf:
        name: pipx

    - name: Install Poetry package manager
      become: true
      ansible.builtin.shell:
        cmd: pipx install poetry
