---
- name: Configure Rofi package
  hosts: localhost

  tasks:
    - name: Install rofi package
      become: true
      ansible.builtin.dnf:
        name: rofi

    - name: Copy rofi dotfile
      ansible.builtin.copy:
        src: rofi/config.rasi
        dest: ~/.config/rofi/

    - name: Copy rofi theme
      ansible.builtin.copy:
        src: rofi/nord.rasi
        dest: ~/.config/rofi/
