---
- name: Customize Sway # https://swaywm.org/
  hosts: localhost

  tasks:
    - name: Install sway
      become: true
      ansible.builtin.dnf:
        name: sway

    - name: Add clipboard integration for neovim
      become: true
      ansible.builtin.dnf:
        name: wl-clipboard

    - name: Install rofi package
      become: true
      ansible.builtin.dnf:
        name: rofi-wayland

    - name: Copy rofi dotfile
      ansible.builtin.copy:
        src: rofi/config.rasi
        dest: ~/.config/rofi/

    - name: Copy rofi theme
      ansible.builtin.copy:
        src: rofi/nord.rasi
        dest: ~/.config/rofi/

    - name: Install brightnessctl
      become: true
      ansible.builtin.dnf:
        name: brightnessctl

    # for i3exit
    # https://github.com/djerveren/i3exit
    - name: Install perl-Gtk3
      become: true
      ansible.builtin.dnf:
        name: perl-Gtk3

    # terminal user interface to manage network connections
    - name: Install nmtui
      become: true
      ansible.builtin.dnf:
        name: nmtui

    # Wayland bar
    - name: Install waybar
      become: true
      ansible.builtin.dnf:
        name: waybar
