---
- name: Customize Sway # https://swaywm.org/
  hosts: localhost

  tasks:
    - name: Install sway
      become: true
      ansible.builtin.dnf:
        name: sway

    - name: Install waybar
      become: true
      ansible.builtin.dnf:
        name: waybar

    - name: Add clipboard integration for neovim
      become: true
      ansible.builtin.dnf:
        name: wl-clipboard

    - name: Install rofi package
      become: true
      ansible.builtin.dnf:
        name: rofi-wayland

    - name: Copy rofi config files
      ansible.builtin.copy:
        src: rofi/config.rasi
        dest: ~/.config/rofi/

    - name: Copy waybar config files
      ansible.builtin.copy:
        src: waybar/
        dest: ~/.config/waybar/

    - name: Copy rofi theme
      ansible.builtin.copy:
        src: rofi/nord.rasi
        dest: ~/.config/rofi/

    - name: Install brightnessctl
      become: true
      ansible.builtin.dnf:
        name: brightnessctl

    # for i3exit
    # https://github.com/djerveren/i3exit
    - name: Install perl-Gtk3
      become: true
      ansible.builtin.dnf:
        name: perl-Gtk3

    # TUI to  manage network connections
    # https://wiki.archlinux.org/title/NetworkManager#Using_iwd_as_the_Wi-Fi_backend
    - name: Install iwd
      become: true
      ansible.builtin.dnf:
        name: iwd
    - name: Install impala
      ansible.builtin.shell:
        cmd: cargo install impala
    - name: Install nmtui
      ansible.builtin.shell:
        dnf: NetworkManager-tui

    # Wayland bar
    - name: Install waybar
      become: true
      ansible.builtin.dnf:
        name: waybar
