---
- name: Customize Sway # https://swaywm.org/
  hosts: localhost

  tasks:
    - name: Install brightnessctl
      become: true
      ansible.builtin.dnf:
        name: brightnessctl

    # for i3exit
    # https://github.com/djerveren/i3exit
    - name: Install perl-Gtk3
      become: true
      ansible.builtin.dnf:
        name: perl-Gtk3
