require("david.set")
require("david.keymap")
require("david.filetree")
require("david.cmp")
require("david.telescope")
require("david.lsp")
require("david.treesiter")
-- require("david.tabby")
-- require("david.lualine")
-- require("david.setups")
-- require("david.signatures")
-- require("david.vimade")
-- require("david.git")
-- -- require("david.colorscheme")
-- require("david.autocmd")
-- require("david.opencode")
