#!/bin/bash
if [ -x /usr/bin/dircolors ]; then
  test -r ~/.dircolors && eval "$(dircolors -b ~/.dircolors)" || eval "$(dircolors -b)"
  alias ls='ls --color=auto'
  alias dir='dir --color=auto'
  alias vdir='vdir --color=auto'

  alias grep='grep --color=auto'
  alias fgrep='fgrep --color=auto'
  alias egrep='egrep --color=auto'
fi

# some more ls aliases
alias ll='ls -l'
alias la='ls -A'
alias l='ls -CF'
alias tmux="TERM=screen-256color-bce tmux"
# alias mutt="TERM=screen-256color-bce mutt"
alias tmuxinator="TERM=screen-256color-bce tmuxinator"
alias dev_env="tmuxinator start dev_env"
alias dev2_env="tmuxinator start dev2_env dev2_env"
alias pj="cd ~/projetos/"
alias unb="cd ~/MEGA/UnB/10_semestre/"
alias empacotamento="cd ~/projetos/empacotamentos/softwarepublico/vagrant"
alias pkg="cd $empacotamento/pkg-rpm"
alias auto="cd ~/projetos/autograss/"
alias rails="/usr/bin/rails"
alias vim="TERM=xterm-256color nvim"
alias nvim="TERM=xterm-256color nvim"
alias spb="cd ~/projetos/spb/softwarepublico"
