#!/bin/bash
if [ -x /usr/bin/dircolors ]; then
  test -r ~/.dircolors && eval "$(dircolors -b ~/.dircolors)" || eval "$(dircolors -b)"
  alias ls='ls --color=auto'
  alias dir='dir --color=auto'
  alias vdir='vdir --color=auto'

  alias grep='grep --color=auto'
  alias fgrep='fgrep --color=auto'
  alias egrep='egrep --color=auto'
fi

# some more ls aliases
alias ll='ls -l'
alias la='ls -A'
alias l='ls -CF'
alias tmux="TERM=screen-256color-bce tmux"
# alias mutt="TERM=screen-256color-bce mutt"
alias tmuxinator="TERM=screen-256color-bce tmuxinator"
alias default_env="tmuxinator start default_env"
alias packing="tmuxinator start empacotamento"
