#!/bin/bash

#. ~/git-completion.bash

force_color_prompt=yes
my_home=/home/david
if [[ -f ~/.bash/colors ]]; then
    . ~/.bash/colors
fi

if [[ -f ~/.bash/aliases ]]; then
    . ~/.bash/aliases
fi


 if [ "$color_prompt" = yes ]; then

if [[ ${EUID} == 0 ]] ; then
    sq_color=$BRed
  else
      sq_color=$BRed
    fi
 S1='\[\e[1;32m\]${debian_chroot:+($debian_chroot)}\u::\[\e[m\]\[\e[1;31m\]\h:\[\e[1;33m\]{\w}\[\e[1;37m\] --> '
 else
 export PS1="$BWhite\342\224\214\342\224\200\[[\e[1;32m\]${debian_chroot:+($debian_chroot)}\u$sq_color\[\e[1;37m\]]::\[[\e[1;31m\]\h\[\e[1;37m\]]\[\e[1;33m\]\n$BWhite\342\224\224\342\224\200>\[[\e[1;37m\]\[\e[1;33m\]\W\[\e[1;37m\]] "
  unset sq_color
 fi

#Personal stuffs
export PATH=$PATH:/home/david/bin
export EDITOR="vim"
# O rofi(i3) precisa desse link simbólico para achar o Telegram
if [ ! -e /usr/bin/Telegram ]; then
    if [ -e $my_home/Downloads/Telegram/Telegram ]; then
        sudo ln -s $my_home/Downloads/Telegram/Telegram /usr/bin/Telegram
    fi
fi

if [ ! -e /usr/bin/studio ]; then
    if [ -e $my_home/Downloads/android-studio/bin/studio.sh ]; then
        sudo ln -s $my_home/Downloads/android-studio/bin/studio.sh  /usr/bin/studio
    fi
fi

xrandr_monitor_casa()
{
    if [[ $1 == 2 ]]; then
        xrandr --output HDMI1 --same-as eDP1 --mode 1280x720
        return
    fi

    if [[ $1 == 1 ]]; then
        xrandr --output eDP1 --mode 1280x720
        return
    fi

    echo "Informe uma opção valida"
}
